title: Akshay Dharmavaram
description: CMU grad student interested in Artificial Intelligence and Robotics
baseurl: "flexton" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Akshay Dharmavaram
author-image:   images/1.jpg
author-job:     Graduate Student
author-loc:     Robotics Institute, CMU
author-advisor: Prof. David Held
author-email:   # Add your email for contant form.
author-twitter: 
about-author:   Hi, I am a gradaute student at CMU, working with Prof. David Held. My research primarily focuses on using Reinforcement Learning for long-term planning and control. Prior to joining CMU, I completed my undergraduate thesis on Hierarchical Reinforcement Learning under Prof. Shalabh Bhatnagar from IISc, Bangalore.

# Social settings
social-twitter:   artemsheludko_
social-facebook:
social-github:    Aks-Dmv
social-pinterest: 
social-instagram: 
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
